apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-app
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: backend
    protocol: TCP
    port: 8080
    targetPort: 8080